# This is a basic workflow to help you get started with Actions

name: checkpatch

# Controls when the workflow will run
on:
  #pull_request:
  #  types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, synchronize]

  # reusable
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkpatch:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repo Name
      run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

    - name: Checkout Repo
      uses: actions/checkout@v4
      id: checkout
      with:
          repository: ${{ github.repository }}
          path: ${{ env.REPO_NAME }} 
          fetch-depth: 0

    - name: Add SSH key
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        required_vars=("SSH_PRIVATE_KEY")
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "Error: Required environment variable $var is not set."
              exit 1
            fi
          done
        mkdir -p ~/.ssh                                                                                                                                                                                                    
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa                                                                                                                                                              
        chmod 600 ~/.ssh/id_rsa                                                                                                                                                                                            
        ssh-keyscan github.com >> ~/.ssh/known_hosts
  
    - name: Checkout Nuttx Repo
      if: ${{ env.REPO_NAME == 'apps' }}
      uses: actions/checkout@v4
      with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: ${{ github.repository_owner }}/nuttx
          ref: ${{ github.head_ref }}
          path: nuttx
          fetch-depth: 0

    - name: Check PR
      run: |
        cd ${{ env.REPO_NAME }}
        commits="${{ github.event.pull_request.base.sha }}..HEAD"
        git log --oneline $commits
        if [ ${{ env.REPO_NAME }} == "apps" ] || [ ${{ env.REPO_NAME }} == "nuttx" ]; then
          echo "::add-matcher::nuttx/.github/nxstyle.json"
          python -m venv .venv
          source .venv/bin/activate
          pip install cmake-format
          echo "../nuttx/tools/checkpatch.sh -u -m -g $commits"
          bash -x ../nuttx/tools/checkpatch.sh -u -m -g $commits
        else
          set -x
          msg=`git show -s --format=%B $commits`
          while read; do
            if [[ $REPLY =~ ^Change-Id ]]; then
              echo "Remove Gerrit Change-ID's before submitting upstream"
              exit 1
            fi
          done <<< "$msg"
        fi
