# This is a basic workflow to help you get started with Actions

name: test-actions

# Controls when the workflow will run
on:
  pull_request:
    types:
      - review

  # reusable
  workflow_call:
    inputs:
      ssh_private_key:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ssh_private_key:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v2
      
    #- name: 设置环境变量
    #  run: |
    #    echo "REPO_PATH=你的repo配置文件的路径" >> $GITHUB_ENV
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update and install git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Download and install repo
      run: |
        mkdir ~/bin
        echo 'export PATH=~/bin:$PATH' >> $HOME/.bashrc
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Verify repo installation
      run: |
        ~/bin/repo --version

    - name: Add SSH key                                                                                                                                                                                                    
      run: |                                                                                                                                                                                                               
        mkdir -p ~/.ssh                                                                                                                                                                                                    
        echo "${{ inputs.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa                                                                                                                                                              
        chmod 600 ~/.ssh/id_rsa                                                                                                                                                                                            
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: repo init
      run: |
        ~/bin/repo init -u git@github.com:zhn-test/manifest.git -b main
        echo "REPO_INIT=true" >> $GITHUB_ENV

    - name: repo sync
      run: |
        ~/bin/repo sync -c -d --no-tags -j12
