# This is a basic workflow to help you get started with Actions

name: test-actions

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    #types:
    #  - review

  # reusable
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
      
    #- name: 设置环境变量
    #  run: |
    #    echo "REPO_PATH=你的repo配置文件的路径" >> $GITHUB_ENV
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Update and install git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Download and install repo
      run: |
        mkdir ~/bin
        echo 'export PATH=~/bin:$PATH' >> $HOME/.bashrc
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Verify repo installation
      run: |
        ~/bin/repo --version

    - name: Add SSH key
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        required_vars=("SSH_PRIVATE_KEY")
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "Error: Required environment variable $var is not set."
              exit 1
            fi
          done
        mkdir -p ~/.ssh                                                                                                                                                                                                    
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa                                                                                                                                                              
        chmod 600 ~/.ssh/id_rsa                                                                                                                                                                                            
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: repo init
      run: |
        ~/bin/repo init -u git@github.com:zhn-test/manifest.git -b main
        echo "REPO_INIT=true" >> $GITHUB_ENV

    - name: repo sync
      run: |
        ~/bin/repo sync -c -d --no-tags -j12

    - name: Fetch PR
      run: |
        REPO_PATH=$(echo "${{ github.event.pull_request.base.repo.full_name }}" | sed 's|/|/.repo/manifests/default.xml|')
        cd $REPO_PATH
        git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
        git checkout pr-branch
        cd -

    - name: Run CI
      run: |
        # 这里添加你的编译或测试命令
        echo "Running CI for all checked out PRs..."
